language: node_js
node_js:
- '6'
- '5'
- '4'
install:
- npm install
deploy:
  provider: npm
  email:
    secure: ObSC6/Djwis4iboBqybF6kKHC3vEEXYN3IpfuqreQR4YnOCj+3Aym4VRfeWFujHStspSi7NXYCA9gpzvwbRrsZZPrAvQPEF3SqIbb5OtIigIwFA6uq1N509HgHrsLqBCF3SoRN4ItZ4qOqh7dZ9OQBagJgPMAe0gxp1utUD50YFamCBIodBdr7158FRWrPgTnxuHR4g+M0tsoDmaNXHlcJwLb4cve3rvhU7L8cNuwKFJkQkKWAHxXnt/urkJLGVNkmDGCodER3TkSBRYAWiFKut8x0No1dpEBNgMwWt9YYGn8jLl3f4j94e0BSGxBWfg+ThDZeDhPnQHAPq/rCcNq0k1iWtFCSC3FUPhr0PELJr2FlUTYrZRNgSwIzpdwd33NhDaKw4o3m6vy1CKqvfuBVJACNvsXAPoBjoRbK0nn/jep2snytwKXlI3VJQFg0l+z9eJcgN1qv2+G7kPs0XmLfV8tHbhVIqxMy5KFzuNbNrBSasolHjgt8BaScrT/qHXeJjj7Ohu3RQrGuOBv1pkSeabUhSiJ0NLgMtpC4NvWww1+8hh+bpqnh88fTaNewSUil6tJRkn0zZ31MI32azgUp1FHK3UO+f3h2Kf27abdqhhOUx55F/u1tzmpvFFScaC40GqqMBEjHOAca9Z13vg4M3ePREtX1M4PADlp58hRZ8=
  api_key:
    secure: i/OWvCrv9cOGS2/xvNFYPJVVkJgLweUsA8PpUSWO8QHeKD8sMIzQUBlqxb8R7Gk0DCmjJ2KBMQ0xxhZSjc4+nzBUmJCHzC0XIABf8X8dWTPSQJ8h9MXRvjTFxCI0yhO831EH2+oOINuIrAvUnzeLyVswJkH/ycgscYmyi6DDUJb5YxOQtCjlAVmbtABc/WaKVESBqRe/A6/r+6DPw/6u0fkhRd7hpAM9GjJtgaro0YazDwy2igI+0QAv3QMR3pwR12e8EIVr9drgu+mW8bVzuqBWZYe8fT/GBgXYS6Oup5tvXjjdV+X7lvMxlepI8p5b9/FDWweNOCPrMqwgxKfiyL4ACHEdM5O2pZ4SSHKjDEFhgaQlQdekmIxnEFk56i5gCqNMX2OeBeHiwi7O0MMkDsPW3u8wzqlf+CaQuSInlhVBF5QbVjWC2GUzSgRT6UlsNNir9QZNaOuY4jNxSchiTnXHlB3hbacnrEAriT25YYMRl4chUEY0f87egs1pGIWEF1PHufDNQijkxwPWvlJqDQFThDlKGswBJwCblo3Iz0LsdeTxXQQ+1uO0ton2ygpCtkHX2ehX6Nugat/pU5YtNDqVc3DuN1VHlJ7ic0N0VNw7YGxU26Pk0+WX6JoF3IehudY95ZmTwQ5hOGSqvxNXKTznIaztvR0thfYhS0LDrSA=
  skip_cleanup: true
  tag: latest
  on:
    node: '6'
    tags: true
